[package]
name = "intervalmusiccompositor-updater"
version = "0.1.0"
authors = ["nw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.26.0"
druid = "0.7.0"
