[package]
name = "intervalmusiccompositor-updater"
version = "0.1.0"
authors = ["nw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.9"
druid = "0.7.0"
dircpy = "0.3.15"
chrono = "0.4"
